### ISSUE TITLE
Critical Error when Plugin in Activated

### ISSUE THREAD

**Issue by cwssysadmin** [agileware/gf-civicrm#5]
When entering the settings of an existing form after activating this plugin, I'm getting a critical error. The WP audit log shows the following ...

```
Stack trace:
#0 /www/public_html/wp-includes/class-wp-hook.php(326): GFCiviCRM\compose_merge_tags()
#1 /www/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#2 /www/public_html/wp-content/plugins/gravityforms/common.php(836): apply_filters()
#3 /www/public_html/wp-content/plugins/gravityforms/common.php(5460): GFCommon::get_merge_tags()
#4 /www/public_html/wp-content/plugins/gravityforms/common.php(5825): GFCommon::gf_vars()
#5 /www/public_html/wp-includes/class-wp-hook.php(324): GFCommon::maybe_output_gf_vars()
#6 /www/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() in /www/public_html/wp-content/plugins/gf-civicrm/gf-civicrm.php on line 119
```

Any clues as to how to remedy this? Issue is with plugin version 1.7.0.

**Comment by cwssysadmin** [comment]
A further update.

Downgrading the plugin to version 1.6.2 allows access to the form settings without a critical error.

Now I need to perform tests to see if this will work.

**Comment by agileware-fj** [comment]
@cwssysadmin  What is the Critical Error?

Also just noting that the function won't work with PHP < 7.1 (although surely you're using at least 8.1, right?) ... everything else that can go wrong inside there should be caught inside of the function.

**Comment by agileware-justin** [comment]
Just noting that in this case, the OP was installing this GF CiviCRM plugin on a site which did not have CiviCRM installed.
