### ISSUE TITLE
Installing this plugin gives a fatal error

### ISSUE THREAD

**Issue by jaapjansma** [agileware/gf-civicrm#6]
Function not civicrm_api3 not found.

I have a wordpress website and civicrm in a remote Drupal installation.

**Comment by agileware-fj** [comment]
Thanks for the report.

Using CiviCRM on a remote installation is not currently supported.  We did have work in progress to support this using CMRF in the [CMRF-experiment branch](/agileware/gf-civicrm/tree/CMRF-experiment) however working with that project was proving too complicated / costly and the experiment was aborted.

**Comment by jaapjansma** [comment]
Ah okay. That was not clear to me. Thanks for updating the documentation

**Comment by agileware-fj** [comment]
No worries, Jaap. Remote support is still planned, just not currently funded.

The canonical issue for adding support of remote CiviCRM is #1
